name: Deploy Apache Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Check website folder
        run: |
          ls -la
          echo "GitHub Actions workflow is working"